# Generated by Django 2.2.4 on 2019-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='projects',
            field=models.ManyToManyField(related_name='components', to='breadboard_app.Project'),
        ),
    ]
