# Generated by Django 2.2.4 on 2019-08-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadboard_app', '0002_auto_20190812_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
