# Generated by Django 2.2.4 on 2019-08-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadboard_app', '0004_auto_20190812_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
