# Generated by Django 2.2.4 on 2019-08-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadboard_app', '0005_auto_20190812_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
