# Generated by Django 2.2.4 on 2019-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadboard_app', '0007_auto_20190813_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='components',
        ),
        migrations.AddField(
            model_name='component',
            name='projects',
            field=models.ManyToManyField(related_name='components', to='breadboard_app.Project'),
        ),
    ]
