# Generated by Django 2.2.4 on 2019-08-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadboard_app', '0008_auto_20190813_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(related_name='projects', to='breadboard_app.Component'),
        ),
    ]
