# Generated by Django 2.2.4 on 2019-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadboard_app', '0009_auto_20190813_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(),
        ),
    ]
